config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  get 'sessions/new'

  get 'page_controller/home'

  get 'about' => 'page_controller#about'

  get 'help' => 'page_controller#help'

  get 'contact' => 'page_controller#contact'

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'

  post 'login' => 'sessions#create'

  delete 'logout' => 'sessions#destroy'

  root 'page_controller#home'

  resources :users

  resources :account_activations, only: [:edit]

  resources :password_resets, only:[:new, :create, :edit, :update]

  end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://railstutorial,org/">Ruby on Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li>
        <%= link_to "About", about_path %>
      </li>
      <li>
        <%= link_to "Contact", contact_path %>
      </li>
      <li>
        <a href="#"> News</a>
      </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class="contianer">
    <%= link_to "sample app", root_path, id: "logo"%>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li> <%= link_to 'All Users', users_path %> </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', '#' %></li>
                <li><%= link_to 'Logout', logout_path, method: "delete" %></li>
              </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shem' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>